# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.100.1"

default_platform :ios

platform :ios do
  before_all do
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
  gym(
  	
  	scheme: 'BankTestApp',
  	clean: true,
  	configuration: 'Debug',
  	project: './BankTestApp.xcodeproj',
  	codesigning_identity: 'iPhone Developer: Manish Malani (9JS9Y7VR2S)',
  	output_directory: "./Build/Release-iPhones",
  	export_method: "ad-hoc",
  	export_options: {
      provisioningProfiles: { 
        "Kode.BankTestApp" => "iPhone Developer: Manish Malani (9JS9Y7VR2S)"

      }
    }
  )
  xcclean
	xcarchive(
  	scheme: "BankTestApp",
  	archive_path: "./Build/Release-iPhones/BankTestApp.xcarchive",
  	output_style: :standard
	)
 dsym_zip(
  archive_path: "./Build/Release-iPhones/BankTestApp.xcarchive",
  dsym_path: "./Build/Release-iPhones/BankTestApp.app.dSYM.zip"
 )
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
